### PR TITLE
Corrected outfit item names

### PR DESCRIPTION
**Pull request by MattiasKro**
coloured-light "necklace" -> colored-light "necklace" floaty prock pants -> floaty rock pants
homoerotic frat-paddle -> orcish frat-paddle
7-fot dwarven mattock -> 7-foot dwarwen mattock
time pants -> time trousers
tropical crimbo pants -> tropical crimbo shorts

### CODE REVIEW

**Comment by m-e-meyer** [comment]
@MattiasKro , the _only_ reason I'm not approving this pull request is because I want pulls from others to go into the dev branch, not the main branch.  I don't know when you'll see this message, so I'm going to make the changes on my copy of the dev branch, now that Real Life allows it.  Thanks!

**Comment by MattiasKro** [comment]
Ok, sorry. I just wanted to help, but I'll promise to merge to the dev beanch next time.

**Comment by m-e-meyer** [comment]
You did help!  I just learned that on my laptop I could do 

git checkout dev
git merge refs/pull/origin/14 

and pull your changes right where I want them to be.  Now they can get in with all the other changes I have to do.  Thanks!

**Comment by MattiasKro** [comment]
Ok, great! Can I close this now?

**Comment by m-e-meyer** [comment]
Hmm.  If I wait until after I've deployed our changes, then I can approve the pull request, which shouldn't do anything because your changes are already there, and you'll be marked as a contributor.  That seems fair.

**Comment by m-e-meyer** [comment]
Interesting.  When I pushed my local main branch to GitHub, GitHub recognized that your commit was present (because I merged it into my dev, which I merged into my main) and closed the pull request.  You are now a contributor!  Congrats!

**Pull request merged**
